/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Legacy (keep for existing code)
        primary: "#0070cc",
        "background-dark": "#0a0f15",
        "surface-dark": "#142438",
        "surface-dark-border": "#1f3347",
        "text-muted": "#8ca8c8",
        // Stitch Material Design 3 color tokens
        "background": "#0f141a",
        "surface": "#0f141a",
        "surface-dim": "#0f141a",
        "surface-bright": "#353a40",
        "surface-container-lowest": "#0a0f15",
        "surface-container-low": "#171c22",
        "surface-container": "#1b2026",
        "surface-container-high": "#252a31",
        "surface-container-highest": "#30353c",
        "surface-variant": "#30353c",
        "surface-tint": "#a5c8ff",
        "on-surface": "#dee3eb",
        "on-surface-variant": "#c1c7d4",
        "on-background": "#dee3eb",
        "primary-container": "#0070cc",
        "on-primary": "#00315e",
        "on-primary-container": "#f0f4ff",
        "on-primary-fixed": "#001c3a",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#a5c8ff",
        "inverse-primary": "#005fae",
        "secondary": "#4edea3",
        "on-secondary": "#003824",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "tertiary": "#b7c8e2",
        "on-tertiary": "#213146",
        "tertiary-container": "#607088",
        "on-tertiary-container": "#eff3ff",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "outline": "#8b919e",
        "outline-variant": "#414752",
        "inverse-surface": "#dee3eb",
        "inverse-on-surface": "#2c3138",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      keyframes: {
        entrance: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        shine: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        entrance: 'entrance 0.6s ease-out forwards',
        float: 'float 3s ease-in-out infinite',
        shine: 'shine 3s ease-in-out infinite',
        fadeInUp: 'fadeInUp 0.5s ease-out',
        marquee: 'marquee 40s linear infinite',
      },
    },
  },
  plugins: [],
}
